hw-1
hordiimariia/mariia-hordii pull request #1
Opened 2022-07-04 22:08 UTC by hordiimariia

2022-07-05 15:29 UTC, KostyantynPanchenko requested changes
Потребує доопрацювання:

- відформатувати весь код відповідно до Java code style (щоб пробіли були там де мають бути і не було там де їм не потрібно бути, наявність та відсутність порожніх стрічок там де потрібно)
- додати коректні модифікатори доступуну до полів/методів/конструкторів - інкапсуляцію ніхто не відміняв

2022-07-05 15:29 UTC, KostyantynPanchenko commented on pom.xml
> +</project>
Прошу звернтуи увагу на червоний знак у рядку 24 та виправити

2022-07-05 15:29 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework1/Main.java
> +}
Прошу виправити

2022-07-05 15:29 UTC, KostyantynPanchenko commented on src/main/java/com/epam/spring/homework1/other/OtherBeanA.java
> +    private final BeanA beanA;
👍 `final`

2022-07-06 08:35 UTC, hordiimariia commented
Відформатувала згідно з зауваженнями

2022-07-06 09:05 UTC, KostyantynPanchenko approved these changes

2022-07-07 21:05 UTC, closed without merging